package com.example.blanball.presentation.navigation

enum class Destinations(val route: String) {
    LOGIN("login"),
    RESET1("reset1"),
    RESET2("reset2"),
    RESET3("reset3"),
    RESET_COMPLETE("reset_complete"),
    REGISTRATION1("registration1"),
    REGISTRATION2("registration2"),
    PUBLIC_PROFILE("publicProfile"),
    ALL_REVIEWS("allReviews"),
    ALL_PLANNED_EVENTS("allPlannedEvents"),
    FILLING_OUT_THE_USER_PROFILE_START("fillingOutTheUserProfileStart"),
    FILLING_OUT_THE_USER_PROFILE1("fillingOutTheUserProfile1"),
    FILLING_OUT_THE_USER_PROFILE2("fillingOutTheUserProfile2"),
    FILLING_OUT_THE_USER_PROFILE3("fillingOutTheUserProfile3"),
    FILLING_OUT_THE_USER_PROFILE4("fillingOutTheUserProfile4"),
    USER_TRAINING_1("userTraining1"),
    USER_TRAINING_2("userTraining2"),
    USER_TRAINING_3("userTraining3"),
    USER_TRAINING_4("userTraining4"),
    HOME("home"),
    FUTURE_EVENTS("future_events"),
    CREATE_NEW_EVENT("create_new_event"),
    RATING("rating"),
    CHATS("chats"),
    FRIENDS("friends"),
    PLANNED_EVENTS("planned_events"),
    NOTIFICATIONS("notifications"),
    SETTINGS("settings"),
    MY_PROFILE("my_profile"),
    VERSIONS("versions"),
    EVENT("event"),
}